BEGIN;
\echo ''
\echo '019_add_id_columns'

ALTER TABLE movie_links
    ADD id bigint GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE people_links
    ADD id bigint GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE trailers           
    RENAME COLUMN trailer_id TO id;

ALTER TABLE casts
    ADD id bigint GENERATED BY DEFAULT AS IDENTITY;

COMMIT;